name: SSMagic
main: hell.supersoul.magic.Main
version: 1.01
depend: [ProtocolLib]

commands:
    magictest:
        description: SS Magic
    statistics:
        description: SS Magic
        aliases: [stat, stats]